version: "3"
services:
  nextjs:
    build: ./frontend
    ports:
      - "3000:3000"
  express:
    build: ./backend
    ports:
      - "3002:3002"

  mysql:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: 


